# ============================================================================================
# GitHub Actions Workflow: Build and Push Docker Image to GitHub Container Registry (GHCR)
#
# This workflow automatically builds a Docker image from the repository source and pushes it
# to GitHub Container Registry (ghcr.io) upon every push to the `main` branch.
#
# Workflow Steps:
#   1. Checkout repository source code.
#   2. Log in to GHCR using GitHub credentials.
#   3. Extract Docker image metadata (tags, labels).
#   4. Build and push the Docker image to GHCR.
#
# Required permissions:
#   - contents: read
#   - packages: write
#
# For details, see: https://github.com/docker/build-push-action
# ============================================================================================

name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files in workspace
        run: ls -alR

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
